import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const runtime = process.env.CUEMIX_NODE_MODULES;
const { chromium } = runtime ? require(`${runtime}/playwright`) : require('playwright');
const out = fileURLToPath(new URL('../artifacts/', import.meta.url));
await mkdir(out, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
const page = await context.newPage();
await page.addInitScript(() => {
  window.testAudio = [];
  const NativeAudio = window.Audio;
  window.Audio = function (...args) { const a = new NativeAudio(...args); window.testAudio.push(a); return a; };
  window.Audio.prototype = NativeAudio.prototype;
  const nativeSource = AudioContext.prototype.createMediaElementSource;
  AudioContext.prototype.createMediaElementSource = function (audio) {
    const source = nativeSource.call(this, audio), connect = source.connect;
    source.connect = function (target, ...args) { if (target instanceof GainNode) audio.testGain = target; return connect.call(this, target, ...args); };
    return source;
  };
});
const errors = []; page.on('pageerror', e => errors.push(e.message));
await page.goto('http://127.0.0.1:4173');
await page.waitForFunction(() => document.querySelector('#workspace').getAttribute('aria-busy') === 'false');
await page.screenshot({ path: out + 'cuemix-empty.png', fullPage: true });
console.log(JSON.stringify({ title: await page.title(), pads: await page.locator('.pad').count(), songs: await page.locator('.song-select').count(), bgms: await page.locator('.bgm-pick').count(), storage: await page.locator('#storage-status').textContent(), errors }));
assert.equal(await page.locator('.pad').count(), 15); assert.equal(await page.locator('.song-select').count(), 5); assert.equal(await page.locator('.bgm-pick').count(), 3);
function wav(seconds) {
  const rate = 8000, samples = Math.floor(seconds * rate), data = Buffer.alloc(44 + samples * 2);
  data.write('RIFF', 0); data.writeUInt32LE(36 + samples * 2, 4); data.write('WAVEfmt ', 8); data.writeUInt32LE(16, 16); data.writeUInt16LE(1, 20); data.writeUInt16LE(1, 22); data.writeUInt32LE(rate, 24); data.writeUInt32LE(rate * 2, 28); data.writeUInt16LE(2, 32); data.writeUInt16LE(16, 34); data.write('data', 36); data.writeUInt32LE(samples * 2, 40);
  for (let i = 0; i < samples; i++) data.writeInt16LE(Math.round(Math.sin(i / rate * Math.PI * 440 * 2) * 1600), 44 + i * 2);
  return data;
}
const longAudio = wav(12);
async function add(selector, name, buffer = longAudio) {
  await page.locator(selector).click();
  await page.locator('#audio-file').setInputFiles({ name: name + '.wav', mimeType: 'audio/wav', buffer });
  await page.locator('#sound-name').fill(name); await page.locator('#save-sound').click();
  await page.waitForFunction(() => !document.querySelector('#edit-dialog').open);
}
await add('#pad-0', '試験ジングル', wav(2));
await add('.song-select[data-id="song-0"]', '試験曲 A');
await add('.song-select[data-id="song-1"]', '試験曲 B');
await add('.bgm-pick[data-id="bgm-0"]', '試験BGM A', wav(2));
await add('.bgm-pick[data-id="bgm-1"]', '試験BGM B');
await add('.bgm-pick[data-id="bgm-2"]', '試験BGM C');
console.log('PASS: 音源の登録');
await page.reload(); await page.waitForFunction(() => document.querySelector('#effect-count').textContent === '1 / 15');
assert.equal(await page.locator('#song-count').textContent(), '2 / 5'); assert.equal(await page.locator('#bgm-count').textContent(), '3 / 3');
await page.locator('.bgm-pick[data-id="bgm-0"]').click(); await page.locator('#bgm-play').click();
await page.waitForFunction(() => document.querySelector('#bgm-state').textContent === '再生中');
await page.waitForTimeout(2400);
assert.ok(await page.evaluate(() => window.testAudio.some(a => a.loop && !a.paused && a.currentTime > 0)));
await page.locator('#bgm-volume').fill('100');
await page.evaluate(() => { const active = window.testAudio.find(a => !a.paused && a.loop); const analyser = active.testGain.context.createAnalyser(); analyser.fftSize = 2048; active.testGain.connect(analyser); window.testAnalyser = analyser; });
await page.waitForTimeout(120);
const baseline = await page.evaluate(() => { const values = new Float32Array(window.testAnalyser.fftSize); window.testAnalyser.getFloatTimeDomainData(values); return Math.sqrt(values.reduce((n,v) => n + v*v, 0) / values.length); });
await page.locator('#bgm-volume').fill('200'); await page.waitForTimeout(120);
const amplified = await page.evaluate(() => { const values = new Float32Array(window.testAnalyser.fftSize); window.testAnalyser.getFloatTimeDomainData(values); return Math.sqrt(values.reduce((n,v) => n + v*v, 0) / values.length); });
assert.ok(baseline > 0); assert.ok(amplified / baseline > 1.85 && amplified / baseline < 2.15, `200% RMS ratio ${amplified / baseline}`);
console.log(`PASS: 実音声の200%増幅（RMS比 ${(amplified / baseline).toFixed(3)}）`);
await page.locator('.bgm-pick[data-id="bgm-1"]').click();
assert.match(await page.locator('#bgm-current').textContent(), /試験BGM A/);
await page.locator('#bgm-play').click(); await page.waitForFunction(() => document.querySelector('#bgm-current').textContent.includes('試験BGM B'));
assert.equal(await page.evaluate(() => window.testAudio.filter(a => !a.paused && a.src && a.volume > 0).length), 1);
await page.locator('#pad-0').click(); await page.waitForFunction(() => document.querySelector('#pad-0').classList.contains('playing'));
assert.equal(await page.evaluate(() => window.testAudio.filter(a => !a.paused && a.volume > 0).length), 2);
await page.locator('#stop-effects').click(); assert.equal(await page.evaluate(() => window.testAudio.filter(a => !a.paused && a.volume > 0).length), 1);
await page.locator('#song-play').click(); await page.waitForFunction(() => document.querySelector('#song-state').textContent === '再生中');
await page.waitForFunction(() => document.querySelector('#bgm-state').textContent === '停止中');
await page.locator('#song-pause').click(); await page.waitForFunction(() => document.querySelector('#song-state').textContent === '一時停止');
await page.locator('#song-play').click(); await page.waitForFunction(() => document.querySelector('#song-state').textContent === '再生中');
await page.locator('#song-seek').fill('500');
assert.ok(await page.evaluate(() => window.testAudio.some(a => !a.paused && a.currentTime >= 6)));
await page.locator('#song-start').click(); assert.ok(await page.evaluate(() => window.testAudio.some(a => !a.paused && a.currentTime < 2)));
await page.locator('.song-select[data-id="song-1"]').click(); assert.equal(await page.locator('#song-current').textContent(), '試験曲 A');
await page.locator('#song-play').click(); await page.waitForFunction(() => document.querySelector('#song-current').textContent === '試験曲 B');
console.log('PASS: 再読込・ループ・選択と再生の分離・重ね再生・自動BGM停止・一時停止・シーク');
await page.locator('#stop-all').click(); assert.equal(await page.evaluate(() => window.testAudio.filter(a => !a.paused && a.src).length), 0);
await page.locator('.bgm-pick[data-id="bgm-0"]').click(); await page.locator('#bgm-play').click(); await page.waitForFunction(() => document.querySelector('#bgm-state').textContent === '再生中');
await page.locator('.bgm-pick[data-id="bgm-1"]').click(); await page.locator('#bgm-play').click();
await page.locator('.bgm-pick[data-id="bgm-2"]').click(); await page.locator('#bgm-play').click();
await page.locator('#stop-all').click(); await page.waitForTimeout(750);
assert.equal(await page.evaluate(() => window.testAudio.filter(a => !a.paused && a.src).length), 0);
console.log('PASS: BGM連続切替中の全停止で再開・残留再生なし');
await page.locator('.intro p').click(); await page.keyboard.press('Digit1'); await page.waitForFunction(() => document.querySelector('#pad-0').classList.contains('playing')); await page.keyboard.press('Space');
assert.equal(await page.evaluate(() => window.testAudio.filter(a => !a.paused && a.src).length), 0);
await page.locator('#fx-volume').fill('42'); await page.waitForTimeout(300);
await page.locator('#song-volume').fill('200');
await page.locator('[data-focus="edit-fx-0"]').click(); await page.locator('#sound-volume').fill('200'); await page.locator('#save-sound').click(); await page.waitForFunction(() => !document.querySelector('#edit-dialog').open);
await page.getByRole('button', { name: '保存・使い方', exact: true }).click();
const downloadPromise = page.waitForEvent('download'); await page.locator('#export-backup').click(); const download = await downloadPromise; const backupPath = await download.path();
await page.waitForFunction(() => !document.querySelector('#export-backup').disabled);
await page.locator('#backup-file').setInputFiles({ name: 'broken.cuemix', mimeType: 'application/octet-stream', buffer: Buffer.from('invalid backup content') });
await page.waitForFunction(() => document.querySelector('#backup-status').textContent.includes('読み込めませんでした'));
assert.equal(await page.locator('#effect-count').textContent(), '1 / 15');
await page.locator('#help-dialog [data-close]').click();
await page.locator('[data-focus="edit-fx-0"]').click();
page.once('dialog', d => d.accept()); await page.locator('#delete-sound').click(); await page.waitForFunction(() => !document.querySelector('#edit-dialog').open);
assert.equal(await page.locator('#effect-count').textContent(), '0 / 15');
await page.getByRole('button', { name: '保存・使い方', exact: true }).click(); page.once('dialog', d => d.accept()); await page.locator('#backup-file').setInputFiles(backupPath);
await page.waitForFunction(() => document.querySelector('#backup-status').textContent.includes('復元しました'));
await page.locator('#help-dialog [data-close]').click(); assert.equal(await page.locator('#effect-count').textContent(), '1 / 15'); assert.equal(await page.locator('#fx-volume').inputValue(), '42');
assert.equal(await page.locator('#song-volume').inputValue(), '200'); assert.equal(await page.locator('#bgm-volume').inputValue(), '200');
await page.locator('[data-focus="edit-fx-0"]').click(); assert.equal(await page.locator('#sound-volume').inputValue(), '200'); await page.locator('#edit-dialog [data-close]').first().click();
console.log('PASS: キー操作・バックアップ復元・不正バックアップ時の既存データ保持・登録解除');
await page.reload(); await page.waitForFunction(() => document.querySelector('#workspace').getAttribute('aria-busy') === 'false');
assert.equal(await page.locator('#song-volume').inputValue(), '200'); assert.equal(await page.locator('#bgm-volume').inputValue(), '200');
await page.locator('[data-focus="edit-fx-0"]').click(); assert.equal(await page.locator('#sound-volume').inputValue(), '200'); await page.locator('#edit-dialog [data-close]').first().click();
console.log('PASS: 再読込後も項目別・個別200%を維持');
await page.screenshot({ path: out + 'cuemix-filled.png', fullPage: true });
for (const width of [1440, 1280, 1024, 800, 375]) { await page.setViewportSize({ width, height: 900 }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `overflow at ${width}`); }
await page.setViewportSize({ width: 1280, height: 900 }); await page.screenshot({ path: out + 'cuemix-1280.png', fullPage: true });
assert.deepEqual(errors, []); console.log('PASS: 幅1440/1280/1024/800/375の横はみ出しなし・ブラウザ例外なし');
await browser.close();
